### ISSUE TITLE
Organization Website URL is set as Text

### ISSUE THREAD

**Issue by gkorland** [omnistrate/saasbuilder#21]
"Organization Website URL" input is set as text should be url and there is no validation for the value.

![image](https://github.com/omnistrate/saasbuilder/assets/753206/cc0c85a3-ec4e-43ab-bc67-3cbbf86e8423)

**Comment by sharmaamits** [comment]
the validation exists and it works, could please retry after clearing the cache and let us know if still see this issue
![image](https://github.com/omnistrate/saasbuilder/assets/34670321/53590053-1cae-4e77-a6f7-1bc8e18e1dea)

**Comment by gkorland** [comment]
![image](https://github.com/omnistrate/saasbuilder/assets/753206/306a5306-f99b-4616-9c8f-89a347868fe5)

**Comment by gkorland** [comment]
You can see the type is not set as URL 
https://github.com/omnistrate/saasbuilder/blob/5520834f51e8ec0470150efd460a51969e40df72/src/features/ProfileSettings/components/ProfileForm.jsx#L124

**Comment by gkorland** [comment]
Ok, I see the fix you can close the issue
