### ISSUE TITLE
Reset password is broken

### ISSUE THREAD

**Issue by gkorland** [omnistrate/saasbuilder#3]
Link points to localhost
```
Hello,

To reset your password, please click here http://localhost:3000/change-password?email=

Thanks
```

**Comment by rushil95** [comment]
Are you running this locally? The domain in the email will take whatever value you configured for the NEXT_PUBLIC_DOMAIN_URL environment variable. So if you configured 'http://localhost:3000', the link in the mail will point to the same.

**Comment by rushil95** [comment]
I saw a hydration error on the page when I ran this locally. Pushed a fix for the hydration error.

**Comment by rushil95** [comment]
Fixed
