### ISSUE TITLE
Service tier should contain the "description" field

### ISSUE THREAD

**Issue by dudizimber** [omnistrate/saasbuilder#87]
**Describe the bug**
The product tier tile should show the product tier description, not (just) the deployment model.

**Screenshots/Videos**
![Screenshot 2024-03-25 at 12 45 50](https://github.com/omnistrate/saasbuilder/assets/16744955/0db99fad-2ed8-4b39-96a2-33e049aa9557)

**Comment by dudizimber** [comment]
@sharmaamits 

![Screenshot 2024-04-02 at 9 48 36](https://github.com/omnistrate/saasbuilder/assets/16744955/4012b675-eb6c-4ccd-9177-441cefd66365)

This is still happening in version 1.0.11. This should show the shorter description defined when creating the Plan Tier, not the long MD description.

**Comment by sharmaamits** [comment]
This is fixed
